package com.composum.assets.commons.event;

import org.apache.sling.api.resource.Resource;
import org.apache.sling.api.resource.observation.ResourceChange;
import org.apache.sling.api.resource.observation.ResourceChangeListener;

import javax.annotation.Nonnull;
import java.util.List;

/**
 * Abstract base class for resource change listeners, providing change filtering capabilities. We also take care
 * that we do not run into a loop and work on events that are generated by ourselves by checking that we work only on
 * events not generated by the service user this service uses.
 */
public abstract class AbstractResourceChangeListener implements ResourceChangeListener {

    // filtern nach change typ und pfad und resourcefilter;
    // zusammenfassen nach pfad; geaenderte properties ignorieren wir;
    // evtl. zusammenfassen zu jcr:content moeglich sein?

    // protected abstract void processChange(ResourceChange.ChangeType changeType, Resource resource);
}
